extends Node


signal level_generated
signal initiate_player
signal deinitialize_player
signal level_end

signal level_transition_show
signal level_transition_finish
signal level_transition_hide
signal loading_level_start
signal loading_level_finshed
